# Travis CI script

language: c

os:
- linux

sudo: false

services:
- docker

env:
  matrix:
  - BUILD_TYPE=default

# osx environment does not have docker
matrix:
  include:
  - env: BUILD_TYPE=valgrind
    os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - uuid-dev
        - valgrind

addons:
  apt:
    packages:
    - uuid-dev

before_install:
- if [ $TRAVIS_OS_NAME == "osx" ] ; then brew update; brew install binutils ; fi

# Build and check this project according to the BUILD_TYPE
script: "/bin/true"
